import type { ContentType } from '../enums';

export type ContentTypeFlags = {
  isArticle: boolean;
  hasAeo: boolean;
  hasFaq: boolean;
  ogType: 'article' | 'website';
  isCourse: boolean;
  isRecipe: boolean;
  difficultyRequired: boolean;
};

export const CONTENT_TYPE_FLAGS: Record<ContentType, ContentTypeFlags> = {
  BlogPost: {
    isArticle: true,
    hasAeo: true,
    hasFaq: true,
    ogType: 'article',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Essay: {
    isArticle: true,
    hasAeo: true,
    hasFaq: true,
    ogType: 'article',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Opinion: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'article',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Tutorial: {
    isArticle: true,
    hasAeo: true,
    hasFaq: true,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  CodeSnippet: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  ShortStory: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Folktale: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Gist: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  QuickNote: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  SeriesOverview: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Course: {
    isArticle: true,
    hasAeo: true,
    hasFaq: false,
    ogType: 'website',
    isCourse: true,
    isRecipe: false,
    difficultyRequired: true,
  },
  CourseLesson: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: true,
    isRecipe: false,
    difficultyRequired: true,
  },
  Devotional: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Book: {
    isArticle: false,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  BookReview: {
    isArticle: false,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Recipe: {
    isArticle: true,
    hasAeo: true,
    hasFaq: true,
    ogType: 'website',
    isCourse: false,
    isRecipe: true,
    difficultyRequired: false,
  },
  Quote: {
    isArticle: false,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  ResearchPaper: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Patent: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  LegalPage: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  AboutMe: {
    isArticle: false,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  PodcastEpisode: {
    isArticle: true,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
  Lyrics: {
    isArticle: false,
    hasAeo: false,
    hasFaq: false,
    ogType: 'website',
    isCourse: false,
    isRecipe: false,
    difficultyRequired: false,
  },
};
