import type { ContentType } from '../enums';
import { CONTENT_TO_SCHEMA_TYPE } from './schema-type-map';

export type SemanticTags = {
  container: string;
  heading: string;
  subheading: string;
  tertiaryHeading: string;
  section: string;
  aside: string;
  footer: string;
  schemaType: string | undefined;
  breadcrumb: boolean;
  comments: boolean;
  toc: boolean;
  nav: boolean;
};

const ARTICLE_TAGS: Omit<SemanticTags, 'schemaType' | 'breadcrumb' | 'comments' | 'toc' | 'nav'> = {
  container: 'article',
  heading: 'h1',
  subheading: 'h2',
  tertiaryHeading: 'h3',
  section: 'section',
  aside: 'aside',
  footer: 'footer',
};

export const CONTENT_SEMANTIC_TAGS: Record<ContentType, SemanticTags> = {
  BlogPost: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.BlogPost,
    breadcrumb: true,
    comments: true,
    toc: false,
    nav: false,
  },
  Essay: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Essay,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: false,
  },
  Opinion: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Opinion,
    breadcrumb: true,
    comments: true,
    toc: false,
    nav: false,
  },
  Tutorial: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Tutorial,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: false,
  },
  CodeSnippet: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.CodeSnippet,
    breadcrumb: false,
    comments: false,
    toc: false,
    nav: false,
  },
  ShortStory: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.ShortStory,
    breadcrumb: false,
    comments: true,
    toc: false,
    nav: false,
  },
  Folktale: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Folktale,
    breadcrumb: false,
    comments: true,
    toc: false,
    nav: false,
  },
  Gist: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Gist,
    breadcrumb: false,
    comments: false,
    toc: false,
    nav: false,
  },
  QuickNote: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.QuickNote,
    breadcrumb: false,
    comments: false,
    toc: false,
    nav: false,
  },
  SeriesOverview: {
    container: 'article',
    heading: 'h1',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.SeriesOverview,
    breadcrumb: true,
    comments: false,
    toc: false,
    nav: true,
  },
  Course: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Course,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: true,
  },
  CourseLesson: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.CourseLesson,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: true,
  },
  Devotional: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Devotional,
    breadcrumb: false,
    comments: true,
    toc: false,
    nav: false,
  },
  Book: {
    container: 'article',
    heading: 'h1',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.Book,
    breadcrumb: true,
    comments: true,
    toc: false,
    nav: false,
  },
  BookReview: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.BookReview,
    breadcrumb: true,
    comments: true,
    toc: false,
    nav: false,
  },
  Recipe: {
    container: 'article',
    heading: 'h1',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.Recipe,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: false,
  },
  Quote: {
    container: 'figure',
    heading: 'figcaption',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.Quote,
    breadcrumb: false,
    comments: false,
    toc: false,
    nav: false,
  },
  ResearchPaper: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.ResearchPaper,
    breadcrumb: true,
    comments: true,
    toc: true,
    nav: false,
  },
  Patent: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.Patent,
    breadcrumb: true,
    comments: false,
    toc: true,
    nav: false,
  },
  LegalPage: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.LegalPage,
    breadcrumb: true,
    comments: false,
    toc: true,
    nav: false,
  },
  AboutMe: {
    container: 'section',
    heading: 'h1',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.AboutMe,
    breadcrumb: false,
    comments: false,
    toc: false,
    nav: false,
  },
  PodcastEpisode: {
    ...ARTICLE_TAGS,
    schemaType: CONTENT_TO_SCHEMA_TYPE.PodcastEpisode,
    breadcrumb: true,
    comments: true,
    toc: false,
    nav: false,
  },
  Lyrics: {
    container: 'article',
    heading: 'h1',
    subheading: 'h2',
    tertiaryHeading: 'h3',
    section: 'section',
    aside: 'aside',
    footer: 'footer',
    schemaType: CONTENT_TO_SCHEMA_TYPE.Lyrics,
    breadcrumb: true,
    comments: false,
    toc: false,
    nav: false,
  },
};
